### ISSUE TITLE
Configuring DNS records

### ISSUE THREAD

**Issue by kafkaesqu3** [kgretzky/evilginx2#135]
I think it would be a great feature to be able to configure DNS records for the evilginx nameserver. 

For example, if I want to set up a mailing server to send phishing emails from the domain I am using with evilginx, there is no way of doing this unless I do not set the glue records and add the A records for my phishlet domains to my registrar panel manually. 

I have been looking at the code to see if this is an easy PR, but I am a Golang noob and this might take some work. 

I love your tool! It is a wonderful way of showing organizations that 2fa is not a silver bullet to all their problems.

**Comment by kaigouthro** [comment]
I've had the issue with the domain name not bringing up anything at all, and only the subdomains i forwarded from dns functioning.

It would be highly advantageous in demonstrating to my clients just why they need to check more than just domain names. (I have 3 brilliant ones that pass for official any day of the week).. 

I myself was the victim of a hack resetting my appleid.. i would love to be able to demonstrate that one as well.. 

I have not yet enabled lures as i am on the fence of ethics about actually exposing client employees secrets, but i'm not sure I understand those anyway, the documentation doesn't add up to me. 

But main point, whatgives with the domain not loading the proxy, only subdomains..

**Comment by GigaByteRex** [comment]
Hi!
I'm experimenting with deploying Evilginx2 as a phishing service, but ran into a problem regarding the following: I'm located in Norway, and Norwegian domains require a "correctly responding DNS server" before you can change the nameservers for the domain. What this means is that since Evilginx2 isn't responding with a authoritative zone file for the domain I'm using, I'm unable to set the Evilginx2 instance as the nameserver for my domain. Of course I can bypass this by simply NOT using Norwegian domains, but that is pretty inconvenient considering most of my engagements are with customers using Norwegian domains. So a feature like this would be highly valuable for me!
