### ISSUE TITLE
Failed to start nameserver on port 53

### ISSUE THREAD

**Issue by NoShortNaame** [kgretzky/evilginx2#137]
Thank you for the big work @kgretzky !
I have an issue at the very beginning of the framework. This issue is displaying :

[!!!] Failed to start nameserver on port 53

Even being Root. I searched a service listening on port 53 but the only one is 'systemd-resolved' in charge of ... DNS

Where am I wrong ?

**Comment by brendancboyle** [comment]
`systemd-resolved` is a local DNS server that is being configured by your hosting provider. Are you using Google Cloud by chance? They force you into using their DNS so that the G Cloud API calls work. This tool works fine without using it as the DNS server, you just have to manually create DNS records on your domain, but it depends on which phishlet you are using. You can easily tell on the enable step because LetsEncrypt will complain about being able to validate the domain.

So for instance if I own phish.com and try to run linkedin, LetsEncrypt will fail because you haven't configured www.phish.com. Just add a CNAME record and run enable again.

**Comment by kgretzky** [comment]
Evilginx acts as a DNS server by itself, so you need to stop and disable any DNS services running on your instance.

**Comment by NoShortNaame** [comment]
Thank you for your answer. I managed to fix this "issue", here is how :

go to `/etc/resolv/conf`
delete `nameserver 127.0.0.53`
add `nameserver 8.8.8.8` and `nameserver 8.8.4.4`

This should help all the `newbies` like me to go through this !

**Comment by azamet90** [comment]
> Evilginx acts as a DNS server by itself, so you need to stop and disable any DNS services running on your instance.

if disable i get this error: [!!!] certdb: get directory at 'https://acme-v02.api.letsencrypt.org/directory': Get https://acme-v02.api.letsencrypt.org/directory: dial tcp: lookup acme-v02.api.letsencrypt.org: Temporary failure in name resolution
