### ISSUE TITLE
request

### ISSUE THREAD

**Issue by ewhitman1** [kgretzky/evilginx2#216]
@kgretzky  is it possible to pass request via custom socks proxy rather than server ip?

**Comment by kgretzky** [comment]
There is no SOCKS support added.

**Comment by valexvictor** [comment]
hey i have configured evilginx on my vps and i have applied socks proxy on my vps via proxychains so that every traffic pass through my socks5 proxy , But evilginx traffic is not passed through it. Does evilginx support Socks proxy. is it possible that end user can see as traffic come to him through my socks5 proxy rather than my server proxy . basically i want my server proxy to be hidden from end users.
