### ISSUE TITLE
Developer mode for running Evilginx locally

### ISSUE THREAD

**Issue by norisharma** [kgretzky/evilginx2#23]
How to implement all through localhost, for test without purchaseing domain and all

**Comment by norisharma** [comment]
How to implement all through localhost, for test without purchaseing domain and all

**Comment by jaykumarjp** [comment]
You mean localhost instead of domain ?

**Comment by norisharma** [comment]
Yes

**Comment by keep-learning-go** [comment]
First understand how domain names work, here are few resources:
https://en.wikipedia.org/wiki/Domain_Name_System
https://en.wikipedia.org/wiki/XAMPP

**Comment by kgretzky** [comment]
This is possible although a bit complicated. First you need to learn how to create self-signed SSL/TLS certificates based off your own CA root cert (there is tons of tutorials on the web showing commands for `openssl` to do just that). Ideally the certificate should have the base domain in `CN` and all hostnames used by the phishlet in `SAN`.

After that, follow these steps:

1. Modify `/etc/hosts` to map all phishing hostnames used by the phishlet with base domain `localdomain.com` to local IP addresss.
```
X.X.X.X www.localdomain.com
X.X.X.X sub1.localdomain.com
X.X.X.X sub2.localdomain.com
```
2. Put your self-signed public certificate with a private key in `~/.evilginx/crt/localdomain.com/` naming them `<phishlet>.crt` (public cert) and `<phishlet>.key` (private key). Here is the listing that will give you an idea of the directory structure:
```
# ls -al ~/.evilginx/crt/localdomain.com/
total 16
drwx------  2 root root 4096 Aug  7 06:35 .
drwx------ 26 root root 4096 Aug  7 06:35 ..
-rw-------  1 root root 3924 Aug  7 06:35 amazon.crt
-rw-------  1 root root 1679 Aug  7 06:35 amazon.key
```

I'm not able to explain it in an easier way. Will probably add a feature for phishlet devs, in the future, to easily use self-signed certs for local development.

**Comment by CyberTheReape** [comment]
bro please help me...I have not been able to deal with evilginx 1  for 1 year ..... now i can't do evilginx2

i have kali linux 2018.2 ...I hang out in some places ..

i have duckdns. 

i have ssl certificate 

accounts-google.duckdns.org    ( my duckdns name)

i am using duckdns adress for localdomain

i am opening 80. port number  in my modem

i am starting apache server

i am starting duckdns adress

my localhost is working with accounts-google.duckdns.org (it is working with https protocol. because i have ssl cerfificate)

now i will delete gmail script in my localhost.

i want use evilginx2 with my duckdns domain name. (because my ssl certificate for  duckdns adress)

please help me now .. 

evilginx what should i do to get my duckdns certificate .. ??

Should I migrate certificates to EvilginX 2 folder????

Should I organize a text document in the folder EviGinx 2????

I have to make a setting after running EvilGinx 2 program ???

please help me.... I worked for a year with evilginx1 but I could not ..I want to work hard with this program.. I want to run evilginx2 program correctly..

do you want to connect to the my computer with team viewer or anydesky ?

please answer me...

**Comment by kgretzky** [comment]
Glad it worked! :smile:

**Comment by kgretzky** [comment]
Evilginx 2.1 now has a full-blown developer mode. Please check the write-up on how to use it:
https://breakdev.org/evilginx-2-1-the-first-post-release-update/

Added with cc17afcfba78778210c9af6149b74f672e71d2d0

**Comment by kinda29487** [comment]
PLEASE SEND ME THE PHISHLET GMAIL PLEASE
akono8u@gmail.com
