### ISSUE TITLE
Option to generate wildcard SSL cert for a phishlet

### ISSUE THREAD

**Issue by byt3bl33d3r** [kgretzky/evilginx2#252]
Hey there!

Apologies if there's already a way to do this that I'm not aware of.

It would be dope if there was an option to generate a wildcard lets encrypt cert for a specific phishlet

The use case here would be to have 2 phishlets configured for 2 diffrent subdomains *but* using the same domain:
e.g.
```
myphish.site.com
wowmyphish.site.com
```

having a wildcard SSL cert would allow to have both those phishlets running on the same box with the same SSL cert.

Cheers & awesome work!

**Comment by kgretzky** [comment]
Hey!

Due to issues with library compatibility in auto-generating wildcard certificates with LetsEncrypt, I couldn't implement that.
It will, though, always generate a certificate for all subdomains included in `proxy_hosts` section of your phishlet. All hostnames with supported subdomains that you need to proxy will be included in SAN.

In the use case scenario you want to use 2 separate phishlets on 2 separate subdomains, which I think is doable at the moment.

Let me know if I didn't understand correctly.
