### ISSUE TITLE
Unknown connections connected to my website in bulk

### ISSUE THREAD

**Issue by reform33d** [kgretzky/evilginx2#286]
Hi, i've been creating a new phishing site with  evilginx and 10 sec after i enable the site (through "phishlets enable instagram") i'm getting spammed by connections on the site, why ? I didn't share the url anywhere, i shared nothing, i can't understand how theses bots can directly know and spot my url. Do you have any ideas where it could come from ?
![image](https://user-images.githubusercontent.com/49880908/56536024-5c838d80-655d-11e9-9b7f-a631e64a9347.png)

**Comment by thehappydinoa** [comment]
I actually encountered the same thing but with only Instagram, I suspect it is something Instagram may have setup to inspect new traffic.

**Comment by reform33d** [comment]
I'm actually having that for every other websites i've tested (Facebook & Twitter). 
I guess i'll try version 2.0 instead of 3.0 one as my browser on PC doesn't even work to load the page while it's working fine on my phone.. can't understand how lmao

**Comment by hash3liZer** [comment]
No, that's with Chrome. Chrome detects the phishing pages. If you are just building a new phishlet, don't do it with chrome, chrome has some algorithms that tries to look for some specific activities in the page and it also put the website as spam if the website reaches a high traffic within just an instance. I've used Chrome in the past and had this problem but Firefox doesn't give this problem.

**Comment by reform33d** [comment]
If Evilgix is simply getting blocked by Chrome, how can it be efficient during Pentest ?  as employees/individuals are 80% using Chrome and not Firefox,

**Comment by hash3liZer** [comment]
Don't blame `evilginx2`. The tool is just perfect for pentest. The question is were you using it for pentest? Cause as far i can think, if i'd be doing some pentesting with evilginx2, it had be in between a few clients, maybe inside some intranet or my own network and chrome would not give any problem with that. By the way, to clear the concern, the problem is not with the evilginx2. There could be many reasons why your website is being flagged as spam. One of the most important one is generating of some unwanted requests while the website loads.

**Comment by reform33d** [comment]
To be honest, i wasn't even using it for anything as it was just for testing the tool, (as i said i didn't spread the link anywhere), that's why i don't understand why Google blacklists it after 10 min. For the fact, i'm having bunch of random connections to my site 15 secs after i enable it, i can't understand why and i believe theses connections are the reason my site is getting considered really fast as malicious by google. A huge amount of trafic is done to the website without me doing anything... 

_### Would you know where it could come from ?_ 

This is how theses random connections to my website look like : 

![image](https://user-images.githubusercontent.com/49880908/56597323-876bf100-65f2-11e9-8367-da88bec45d7a.png)

**Comment by reform33d** [comment]
You mentionned "unwanted requests" which are being generated, do you have any ideas why they are getting generated ?

**Comment by hash3liZer** [comment]
Actually, they are not unwanted requests, they are important as well. But the problem is let's say for example, a request should be sent to `horizon.google.com.yourfakedomain.com` but it instead it is being sent to the orignal domain `horizon.google.com`. In case of google, i've noticed several endpoints being bricked due to this behaviour. To make it completely work, i guess you have to replace all the occurences of the orignal urls with their possible fake urls. But remember, that's where the problems starts. You have to analyze every JS file from the website, and surely sites like google, protonmail, and blockchain contains like millions of lines of code which is pretty difficult and time-consuming task to perform.

**Comment by xornion** [comment]
Avoid free domain services

**Comment by GregorioSecurity** [comment]
I've had this issue as well, if you run a netstat on your box you can see all of the IP addresses connecting to your box. Most of them are probably coming from Russia and China, just make sure that you put appropriate firewall rules on your web server. For testing purposes just only open port 80 and 443 to the public IP address of the network you are testing from. Simple command for Ubuntu: `sudo ufw delete [row number of open port 80]`
`sudo ufw allow proto tcp from [public ip] to 0.0.0.0/0 port 80`
You can get your public ip address from ipchicken.com.
