### ISSUE TITLE
cacme: error: 400  :: urn:ietf:params:acme:error:malformed :: No embedded JWK in JWS header, url: 

### ISSUE THREAD

**Issue by Birdmanca** [kgretzky/evilginx2#375]
i have set my own domain lovefacebook.cf 
with WWW.FACEBOOK.COM CNAME external ip 
       M.FACEBOOK.COM CNAME  external ip 
set everything . 
when i tried to enable phishlets for facebook i have same error offen 
failed to load certificate files for phishlet 'facebook', domain 'lovefacebook.cf': open /root/.evilginx/crt/lovefacebook.cf/facebook.crt: no such file or directory
[05:15:39] [inf] requesting SSL/TLS certificates from LetsEncrypt...
[05:15:40] [!!!] acme: error: 400 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-acct :: urn:ietf:params:acme:error:malformed :: No embedded JWK in JWS header, url: 
[05:15:40] [inf] disabled phishlet 'facebook'

![Screenshot from 2019-10-19 05-29-08](https://user-images.githubusercontent.com/55595042/67138395-ec1aa800-f231-11e9-9487-35700e281af2.png)

**Comment by azamet90** [comment]
hmm looks like issues will be closed without answer :( same problem i do have now

**Comment by evilginxclient** [comment]
Try it:

npm install --save @root/acme

var ACME = require('@root/acme');

**Comment by jsmit260** [comment]
@evilginxclient  - Where do you place the "var ACME = require('@root/acme');" snippet?

**Comment by azamet90** [comment]
> Try it:
> 
> npm install --save @root/acme
> 
> var ACME = require('@root/acme');

What i not understand is on debian it is giving zero error but after creating url and waiting 1 hour ör so it is letting firefox give pushing url error which is complete red

**Comment by horllste** [comment]
hmmm, did you setup your glue records?

**Comment by ralphte** [comment]
You need to open port 80

**Comment by adisunshine1978** [comment]
I am a novice and am having the same issue can someone help willing to pay

**Comment by 3vall** [comment]
I had the same problem and this is how I solved it. 

First, why are you seeing this issue:
This issue is when you haven't set your` A record` (DNS Settings of your domain) probably for the subdomains your phislet needs and instead of adding the A records to your subdomain, you keep enabling phislet. 

How to solve it: 
1: Quit your evilgnix
2: Add `A records` for all of your subdomains. e.g for outlook you need to add 3 records for these subdomains login.yourdomain.com, account.yourdomain.com, outlook.yourdomain.com
3: start evilginix again and enable template now. That's all
