### ISSUE TITLE
Feature Request: Option to disable / configure the URL tokenization

### ISSUE THREAD

**Issue by edermi** [kgretzky/evilginx2#48]
It would be nice if it was possible to (partly) turn off the URL tokenization or at least give some configuration options. I'm totally aware why this is done and in most cases this makes absolutely sense, but there are scenarios where we are interacting with victims directly, e.g. via phone call or face to face. It is not feasible to dictate such a long token and explain the victim why it is sent to youtube when it had a typo.

To prevent sites from getting flagged by bots crawling CT logs like you described in your blog post, some other configuration options might be useful, e.g.:

- Restrict source IP address (in case of attacks targeted against customers, this information is easy to gather and also makes sure that no other Internet citizens are harmed by accident) - feasible implementation
- Check if the site is crawled by a legit browser (e.g. via User Agent, or, advanced, via some Javascript Foo) - but I think this is hard to do, to keep up with browser development and some bots will still use chrome/firefox headless. Not the best idea.
- Configurable short-URLs like "/owa" or "/login" - Users have seen enough of them to type them correctly and they look legit - probably the simplest to implement?
- Make the evilness happen after the bots where there, e.g. by waiting $timeframe after setting up the server and certificates before actually doing the nasty mitm stuff. The effectiveness may be determined by simply doing some testig.

**Comment by kgretzky** [comment]
Thanks for suggestions! Truly awesome ideas.

> Restrict source IP address (in case of attacks targeted against customers, this information is easy to gather and also makes sure that no other Internet citizens are harmed by accident) - feasible implementation

This is a good idea. Phishlet would specify the IP mask that it allowed connections from e.g. `45.9.0.0/16`.

> Check if the site is crawled by a legit browser (e.g. via User Agent, or, advanced, via some Javascript Foo) - but I think this is hard to do, to keep up with browser development and some bots will still use chrome/firefox headless. Not the best idea.

Yes, this would not work right, since it is too hard to identify bots by fingerprinting like this.

> Configurable short-URLs like "/owa" or "/login" - Users have seen enough of them to type them correctly and they look legit - probably the simplest to implement?

This I can't implement unfortunately as it would break the full mitm proxy capabilities of Evilginx. Since Evilginx proxies the target website 1:1, it would try to access the paths as they are on the target server. But maybe I can think of something - it can make an exception for some paths and have them act as redirectors. Will look into it!

> Make the evilness happen after the bots where there, e.g. by waiting $timeframe after setting up the server and certificates before actually doing the nasty mitm stuff. The effectiveness may be determined by simply doing some testig.

Yes! Good idea. I had something like that in my mind. Something similar to how Cloudflare's "we're checking your browser" thing works before accessing the target website.

Thanks!

**Comment by 001mofo** [comment]
I second this request.    Also suggest maybe a way to toggle the unauthorized redirect on/off, for predetermined amount of time.

**Comment by kgretzky** [comment]
Custom phishing URL added in version 2.3.0.
