### ISSUE TITLE
Changing parameter values is not effective in the same evilginx- 2.4.0

### ISSUE THREAD

**Issue by pawp81** [kgretzky/evilginx2#498]
1. I configured lure to use pre-phishing HTML template (I am using download_example.html)
2. I generate phishing URL with from_name and filename for the URL by running:
`lures get-url 12 from_name="John Doe" filename="Annual Salary Report.xlsx"`
URL is generated:
https://my_phishing_FQDN/COemWJhU?owI=pm2pyiKLAVQpd3cy8QR2JBzJmnDHExFdeQaYzO24E_79cD-L8J37tomYSZO9guEnBXb2EkeWrjP5Q-lx
3. I test it in the web browser and from_name and filename parameters are correctly populated with information from URL's parameter
4. I generate new URL for the same URL by running with different parameters values:
`lures get-url 12 from_name="Megan Bowen" filename="Annual Salary Report 2020.xlsx"`
https://my_phishing_FQDN/COemWJhU?cQ=6vfId77GLEePEsqSRl3t1NsbVsAwhJ6ouaGpOzyqsK6q9Wl107vagiidWAtjcu27JjljVT0IGSqHgnckvoycmctAYSo
5. When I open new link in the web browser I get old from_name (John Doe) and filename (Annual Salary Report 2020.xlsx)

Closing and re-opening evilginx allows me to generate URL with new from_name and filename.

I noticed that if I don't test the URL in step 3, then when I change from_name and filename parameters and browse to the URL I get the values of from_name and filename after the change.

**Comment by kgretzky** [comment]
Thanks for reporting.

This is expected behavior. The custom parameters are permanently set for the current session, so even if you open up a new URL with new parameters embedded, it will still use the parameters from the first already opened session. The only way to reset the session's custom parameters is restarting Evilginx, which will kill all active sessions.

This is only an issue for testing environments and won't affect normal phishing operations.

**Comment by pawp81** [comment]
I wonder how do you foresee normal phishing operations with the parameters? Based on your explanation yt means that pre-phish HTML page can be customized for single user only in single Evilginx session, right? While in normal phishing operation attacker would like to sent the campaign to his list of victims.
Let me know if I am wrong.
