### ISSUE TITLE
Multiple collaborators

### ISSUE THREAD

**Issue by JamesCullum** [kgretzky/evilginx2#505]
Hey @kgretzky ,

I believe it might make sense to support you in managing the Github projects.
There was a longer time of inactivity, and @hash3liZer and I kept working on the fork.

Maybe it's a good idea for this repository to add some contributors with write permission, so that we can make sure the PRs, issues etc are reviewed and merged in the future as well.

**Comment by kgretzky** [comment]
Hey James!

Thank you and sorry for late response. I've just checked the fork and it looks great. I'm super glad that you are finding the time to fix issues in evilginx on your own. This is a great idea although I'd prefer to be implementing the fixes on my own when I have time. I know I could be doing much better in maintaining this project as I don't have that much time for it. As much as I'd like to add you guys as active collaborators I feel it would generate additional work overhead for me to be verifying the changes and I simply do not have the time :(

I think it is best if you continued to maintain the fork and I can link to it here in case anyone wants to use evilginx version with faster fixes :). Please do send some links to your commits on the fork, when you can, so that I can look into them and reimplement the fixes here in the base repo.

**Comment by JamesCullum** [comment]
Sure, got it. I've PRed some changes here: https://github.com/kgretzky/evilginx2/pull/504
