### ISSUE TITLE
Coudnt connect to internet issue

### ISSUE THREAD

**Issue by Muhasheikh** [kgretzky/evilginx2#534]
Hey.iam testing out this in a lan enviroment.after like 5 or 6 attempts it displays "we coudnt connect to indtagram make sure you are connected to internet"
Any fix for it 
![Screenshot_20201031-212329__01](https://user-images.githubusercontent.com/63383715/97830417-e5eb5280-1cf2-11eb-89e4-2d372fb3c669.jpg)

**Comment by kabilyazici** [comment]
I also have this problem. I created a site on the internet for testing purposes. Everything is working normally but after a few days I get this problem. I can't find where the problem is. I installed the tool on Ubuntu Server 20.04 LTS. If anyone can help, I will ask another question. I really need help.

**Comment by onceonce1** [comment]
+++  I have same problem, help pls

**Comment by onceonce1** [comment]
or give  link on post
