### ISSUE TITLE
Does evilginx have an endpoint to send custom data/tokens?

### ISSUE THREAD

**Issue by UndergroundLabs** [kgretzky/evilginx2#752]
I am using Javascript inject to get some values from the page. I need these values stored, does Evilginx have an endpoint where I can send these tokens so they appear in the session list?

For example, if the page has some tokens in the HTML that I want to grab with Javascript, can I make an ajax request to evilginx to store this data with the session?

**Comment by JM-Lemmi** [comment]
No, Evilginx currently does not have this functionality.

**Comment by 456478** [comment]
you can create a **custom** credential capture regex. get the tokens via javascript then post them against evilginx2 so they are picked up as credentials.

**Comment by Support-1535** [comment]
Hello! If you were already able to resolve your doubts and achieve your goals, close the issue so that we know which ones are pending.

Thank you!

If you want expedited help and have the assistance of many professional people, join our private group. Contact us support@evilginx2.com to give you access to the group.
