### ISSUE TITLE
How to change headers

### ISSUE THREAD

**Issue by kileyturney** [kgretzky/evilginx2#767]
I have some problems
1) On original request on submitting form server returns 302 Found status with HTTP/2 protocol. But when I am use evilginx it uses HTTP/1.1. So, how I can change that evilginx use HTTP/2
2) Why in phishlet sub_filters not working when auto_filter is false? I am try change url manually but it not working. It changed only when auto_filter is true

**Comment by Web3villian666** [comment]
Get help from support mate. https://icq.im/mrgretzky he's helped work my custom phishlets

**Comment by Support-1535** [comment]
Hello! If you were already able to resolve your doubts and achieve your goals, close the issue so that we know which ones are pending.

Thank you!

If you want expedited help and have the assistance of many professional people, join our private group. Contact us support@evilginx2.com to give you access to the group.
