### ISSUE TITLE
How to add nginx proxy between victim and evilginx2

### ISSUE THREAD

**Issue by kileyturney** [kgretzky/evilginx2#790]
I am try to add Nginx reverse proxy before Evilginx2
So, Nginx have address site1.com, Evilginx - site2.com
On Nginx I am got certificates for domain and other settings, but when I am go to site1.com I am have error 'too_many_redirects'
But if in Nginx settings I am set any other site (site3.com) then all traffic proxied.
Why not working Nginx proxy with Evilginx?
Anybody have working methods?

**Comment by Support-1535** [comment]
Hello! If you were already able to resolve your doubts and achieve your goals, close the issue so that we know which ones are pending.

Thank you!

If you want expedited help and have the assistance of many professional people, join our private group. Contact us support@evilginx2.com to give you access to the group.
