### ISSUE TITLE
Chrome is able to detect evilginx2 url

### ISSUE THREAD

**Issue by Hawaii487** [kgretzky/evilginx2#816]
Evilginx2 url is giving red flag because of bot scanners help me enable it for only one IP so that the bots IP will be blocked

**Comment by Hawaii487** [comment]
I need help

**Comment by ReshSenki** [comment]
I can help

**Comment by Jackramsdel** [comment]
@Mrgretzky on icq helped me with that..... It was x-evilginx header something that's how they detect it... can help out

**Comment by lhost25** [comment]
> @Mrgretzky on icq helped me with that..... It was x-evilginx header something that's how they detect it... can help out

you need to stop advertising this your scam shit else you will be ban.

**Comment by Support-1535** [comment]
Hello! If you were already able to resolve your doubts and achieve your goals, close the issue so that we know which ones are pending.

Thank you!

If you want expedited help and have the assistance of many professional people, join our private group. Contact us support@evilginx2.com to give you access to the group.
