### ISSUE TITLE
Question about authentification URL 

### ISSUE THREAD

**Issue by Arasteus** [kgretzky/evilginx2#819]
#### REPORT ONLY BUGS OR FEATURE SUGGESTIONS.

Hello guys,

I'm creating some phishlets and it's working fine except one where:
1) Cookies are dynamicly generated so I used authentification URL

However, if my authentification URL is semi randomly generated such as :  
successlogin.do?nonce={random}
I tried to do like 
auth_url = '/successlogin.do*'
However the session capture does not work, the log says "One authentification token captured" and then nothing else.
Has someone made it work auth_url with regexp ?

Thank you

**Comment by Arasteus** [comment]
But then it will end the session capture even if the guy has not put his credentials

**Comment by Support-1535** [comment]
Hello! If you were already able to resolve your doubts and achieve your goals, close the issue so that we know which ones are pending.

Thank you!

If you want expedited help and have the assistance of many professional people, join our private group. Contact us support@evilginx2.com to give you access to the group.
