### ISSUE TITLE
Internal Test

### ISSUE THREAD

**Issue by secuhiro** [kgretzky/evilginx2#823]
#### REPORT ONLY BUGS OR FEATURE SUGGESTIONS.

I have tried evilginx2 on one platform.
I mean I set the evilginx2 on Kali linux and access the lure URL from Firefox on the same kali linux

I set like below
: config domain git.phis
: config ip 127.0.0.1
: phishlets hostname github git.phis
: phishlets enable github
: lures create github
: :lures edit 0 redirect_url https://www.facebook.com/
: lures get-url 0

and get  lure URL
So I access the URL from Firefox on the same kali linux but cannot access "Server not found".
(I can access any normal internet site from Firefox on the same kali linux)

Would you please advise me How I can fix it?

**Comment by Support-1535** [comment]
Hello! If you were already able to resolve your doubts and achieve your goals, close the issue so that we know which ones are pending.

Thank you!

If you want expedited help and have the assistance of many professional people, join our private group. Contact us support@evilginx2.com to give you access to the group.
