### ISSUE TITLE
cookie notification won't turn off

### ISSUE THREAD

**Issue by ozhgod342** [kgretzky/evilginx2#825]
![not](https://user-images.githubusercontent.com/79153101/186740376-8bfb1d77-1dfc-4073-b691-4d341a1766d2.PNG)

I can't log in because it doesn't go from the screen, how can I solve it?

**Comment by rzmpzgeviii** [comment]
@ozhgod342 I got the exact same god damn problem. Did you find the solution?

**Comment by Support-1535** [comment]
Hello! If you were already able to resolve your doubts and achieve your goals, close the issue so that we know which ones are pending.

Thank you!

If you want expedited help and have the assistance of many professional people, join our private group. Contact us support@evilginx2.com to give you access to the group.
