### ISSUE TITLE
Lure link keeps redirecting to the YouTube video

### ISSUE THREAD

**Issue by voldemortxx** [kgretzky/evilginx2#826]
![evilginxReport2](https://user-images.githubusercontent.com/100381933/186961054-d85f0b99-7d72-472b-aec8-bc9f6866319f.png)

The lure link below, when opened automatically redirects to the youtube video. am I getting any config wrong?

**Comment by ghoxt007** [comment]
i can set up evilginx and i have working phishlets telegram me @ghoxt007

**Comment by Support-1535** [comment]
Hello! If you were already able to resolve your doubts and achieve your goals, close the issue so that we know which ones are pending.

Thank you!

If you want expedited help and have the assistance of many professional people, join our private group. Contact us support@evilginx2.com to give you access to the group.
