### ISSUE TITLE
unauthorized request

### ISSUE THREAD

**Issue by ZeroD-inc** [kgretzky/evilginx2#863]
#### REPORT ONLY BUGS OR FEATURE SUGGESTIONS.

DELETE

**Comment by longwalkshortdock999** [comment]
Phishlets 4 sale  TD, cibc, rbc, bmo, chase canada and others my telegram allowesvama ddgvwsewve



Sent from my Galaxy


-------- Original message --------
From: Z3ROD ***@***.***>
Date: 2022-11-08 1:06 a.m. (GMT-08:00)
To: kgretzky/evilginx2 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [kgretzky/evilginx2] unauthorized request (Issue #863)


DO NOT ASK FOR PHISHLETS.
DO NOT ASK FOR HELP CREATING PHISHLETS.
DO NOT ASK TO FIX PHISHLETS.
DO NOT ADVERTISE OR TRY TO SELL PHISHLETS.
EXPECT A BAN OTHERWISE. THANK YOU!
REPORT ONLY BUGS OR FEATURE SUGGESTIONS.

**Comment by longwalkshortdock999** [comment]
my telegram @diam0ndfox



Sent from my Galaxy



-------- Original message --------
From: Z3ROD ***@***.***>
Date: 2022-11-08 1:06 a.m. (GMT-08:00)
To: kgretzky/evilginx2 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [kgretzky/evilginx2] unauthorized request (Issue #863)


DO NOT ASK FOR PHISHLETS.
DO NOT ASK FOR HELP CREATING PHISHLETS.
DO NOT ASK TO FIX PHISHLETS.
DO NOT ADVERTISE OR TRY TO SELL PHISHLETS.
EXPECT A BAN OTHERWISE. THANK YOU!
REPORT ONLY BUGS OR FEATURE SUGGESTIONS.
